
            <?php 
            if (store::getConfigValue('maintenance_mode') == 0) {
                ?>
                <nav class="dvbb-navigation dvbb-navigation-top dv-grid-row">
                    <div class="dv-grid-column-12 dvbb-navigation-top-left">
                        <a href="<?=store::getRouter()->generate('home');?>">index</a>
                        <?php 
                        if (auth::getUser()) {
                            ?>
                            - <a href="<?=store::getRouter()->generate('user-list');?>">user list</a> 
                            - <a href="<?=store::getRouter()->generate('user-settings');?>">settings</a>
                            <?php 
                        }
                        ?>
                    </div>
                    <div class="dv-grid-column-12 dvbb-navigation-top-right">
                        <?php
                        if (auth::getUser()) {
                            ?>
                            Logged in as <?=auth::getUser()->username?> - 
                            <a href="#" class="dvbb-logout-link" data-ajax-url="<?=store::getRouter()->generate('ajax-logout');?>">logout</a>
                            <?php 
                            if (auth::can('admin')) {
                                ?>
                                - <a href="<?=store::getRouter()->generate('admin');?>">admin</a> 
                                <?php 
                            }
                        } else {
                            ?>
                            <a href="#" class="dvbb-login-link">login</a> - 
                            <a href="<?=store::getRouter()->generate('register');?>">register</a>
                            <?php 
                        }
                        ?>
                    </div>
                </nav>
                <div class="dvbb-login-form dvbb-subnavigation dv-grid-row" style="display: none;">
                    <form method="post" action="<?=store::getCurrentUrl()?>">
                        <div class="dv-grid-column-9">
                            <input type="text" name="username" placeholder="username" class="dv-form-element" />
                        </div>
                        <div class="dv-grid-column-1"></div>
                        <div class="dv-grid-column-9">
                            <input type="password" name="password" placeholder="password" class="dv-form-element" />
                        </div>
                        <div class="dv-grid-column-1"></div>
                        <div class="dv-grid-column-4">
                            <input type="submit" value="login" class="dv-form-button dv-width-100" data-ajax-url="<?=store::getRouter()->generate('ajax-login');?>" />
                        </div>
                    </form>
                    <div class="dv-grid-column-10"></div>
                    <div class="dv-grid-column-9"><small><a href="<?=store::getRouter()->generate('password-reset')?>">forgot your password?</a></small></div>
                </div>
                <?php 
            }
            ?>