<?php 
$forum = (new forum())->getById(app::getViewParam('id'));
?>
<div class="dvbb-forum-container">
    <strong class="dvbb-category-title"><?=$forum->title?></strong>
    <div class="dvbb-legend dv-grid-row">
        <div class="dv-grid-column-13 dv-text-bold">Thread / Author</div>
        <div class="dv-grid-column-2 dv-text-bold">Replies</div>
        <div class="dv-grid-column-2 dv-text-bold">Views</div>
        <div class="dv-grid-column-7 dv-text-bold">Last Post</div>
    </div>
</div>
<?php 
$posts = (new post())->getByField('forum_id', $forum->id);
if (count($posts) > 0) {
    foreach ($posts as $post) {
        $url = app::getRouter()->generate('post', array('id' => $post->id));
        $subPosts = count((new post())->getByField('parent_id', $post->id));
        ?>
        <div class="dvbb-forum dv-grid-row">
            <div class="dv-grid-column-1">&bull;</div>
            <div class="dv-grid-column-12">
                <a href="<?=$url;?>"><?=$post->title;?></a><br />
                <small style="color: grey"><?=$post->user_id;?></small>
            </div>
            <div class="dv-grid-column-2"><?=$subPosts;?></div>
            <div class="dv-grid-column-2">--</div>
            <div class="dv-grid-column-7">--</div>
        </div>
        <?php
    }
} else {
    ?>
    <div class="dvbb-forum dv-grid-row">
        <div class="dv-grid-column-24">
            <span class="dv-color-notice">No posts yet.</span>
        </div>
    </div>
    <?php 
}
