<?php 
$post = (new post())->getById(app::getViewParam('id'));
?>
<div class="dvbb-forum-container">
    <strong class="dvbb-category-title"><?=$post->title?></strong>
    <div class="dvbb-forum dv-grid-row">
        <div class="dv-grid-column-24">
            <?=$post->body?>
        </div>
    </div>
    <div class="dvbb-forum dv-grid-row">
        <small class="dv-grid-column-24 dv-color-notice">
            <?=$post->created_at?>
        </small>
    </div>
<?php 
$subPosts = (new post())->getByField('parent_id', $post->id);
if (count($subPosts) > 0) {
    foreach ($subPosts as $subPost) {
        ?>
        <strong class="dvbb-category-title"><?=$subPost->title?></strong>
        <div class="dvbb-forum dv-grid-row">
            <div class="dv-grid-column-24">
                <?=$subPost->body?>
            </div>
        </div>
        <div class="dvbb-forum dv-grid-row">
            <small class="dv-grid-column-24 dv-color-notice">
                <?=$subPost->created_at?>
            </small>
        </div>
        <?php
    }
}