<?php 
$forum = app::getViewByKey('forum');
?>

<nav class="dv-grid-row dvbb-subnavigation">
    <div class="dv-grid-column-12 dvbb-subnavigation-left">
        <?=app::getConfigKey('posts_per_page')?> topics per page: 
        <?php
        $pages = array();
        for ($i = 1; $i <= app::getViewByKey('pageTotal'); $i++) {
            $param = '';
            if ($i > 1) {
                // only now do we actually add a parameter
                $param = '?page=' . $i;
            }
            // check if current page is 1 or otherwise
            $active = null;
            if (app::getViewByKey('page') && app::getViewByKey('page') == $i) {
                // not page 1 but we ARE on this page
                $active = 'active';
            } elseif (!app::getViewByKey('page') && $i == 1) {
                $active = 'active';
            }
            $pages[] = '<a href="' . app::getCurrentUrl() . $param . '" class="dvbb-pagination-link ' . $active . '">' . $i .'</a>';
        }
        if (count($pages) > 1) {
            echo $pages = implode(' ', $pages);
        } else {
            echo $pages = '<a href="' . app::getCurrentUrl() . '" >1</a>';
        }
        ?>
    </div>
    <div class="dv-grid-column-12 dvbb-subnavigation-right">
        <?php 
        if (auth::getUser()) {
            ?>
            <a href="<?=app::getRouter()->generate('topic-create', array('id' => $forum->id));?>">new topic</a>
            <?php 
        }
        ?>
    </div>
</nav>

<div class="dvbb-container dvbb-forum-list">
    <div class="dvbb-container-header"><?=$forum->title?></div>
    <div class="dvbb-container-legend dv-grid-row">
        <div class="dv-grid-column-15">Thread / Author</div>
        <div class="dv-grid-column-2">Replies</div>
        <div class="dv-grid-column-7">Last Post</div>
    </div>
    <?php 
    $topics = app::getViewByKey('topics');
    if (count($topics) > 0) {
        foreach ($topics as $topic) {
            // set unread status to false
            $unread = false;
            
            $unreadStatus = $topic->getUnreadStatus();
            if ($unreadStatus === null || $topic->last_post_at > $unreadStatus->created_at) {
                $unread = true;
            }
            
            $url = app::getRouter()->generate('topic', array('id' => $topic->id));
            $subPosts = count((new post())->getByField('parent_id', $topic->id));
            $user = (new user())->getById($topic->user_id);
            ?>
            <div class="dvbb-container-row dv-grid-row">
                <div class="dv-grid-column-1">
                    <div class="dvbb-read-status<?=($unread ? ' unread' : '');?>"></div>
                </div>
                <div class="dv-grid-column-14">
                    <a href="<?=$url;?>"><?=$topic->title;?></a><br />
                    <small style="color: grey"><?=$user->username;?> - posted <?=$topic->created_at?></small>
                </div>
                <div class="dv-grid-column-2"><?=$subPosts;?></div>
                <div class="dv-grid-column-7"><?=$topic->last_post_at?></div>
            </div>
            <?php
        }
    } else {
        ?>
        <div class="dvbb-container-row dv-grid-row">
            <div class="dv-grid-column-24">
                <span class="dv-color-notice">No posts yet.</span>
            </div>
        </div>
        <?php 
    }
    ?>
</div>

<nav class="dv-grid-row dvbb-subnavigation">
    <div class="dv-grid-column-12">
        <?=app::getConfigKey('posts_per_page')?> topics per page: 
        <?=$pages;?>
    </div>
    <div class="dv-grid-column-12 dvbb-subnavigation-right">
        <?php 
        if (auth::getUser()) {
            ?>
            <a href="<?=app::getRouter()->generate('topic-create', array('id' => $forum->id));?>">new topic</a>
            <?php 
        }
        ?>
    </div>
</nav>