<?php 
$forum = store::getViewValue('forum');
$posts_per_page = tool::getPostsPerPage();

// separate sticky from normal topics, we do this like this to prevent multiple queries where unnecessary
$topics = store::getViewValue('topics');
$stickyTopics = array();
$normalTopics = array();
foreach ($topics as $topic) {
    if ($topic->sticky) {
        $stickyTopics[] = $topic;
    } else {
        $normalTopics[] = $topic;
    }
}
?>

<nav class="dv-grid-row dvbb-subnavigation">
    <div class="dv-grid-column-12 dvbb-subnavigation-left">
        <?=$posts_per_page?> topics per page: 
        <?php
        $pages = array();
        for ($i = 1; $i <= store::getViewValue('pageTotal'); $i++) {
            $param = '';
            if ($i > 1) {
                // only now do we actually add a parameter
                $param = '?page=' . $i;
            }
            // check if current page is 1 or otherwise
            $active = null;
            if (store::getViewValue('page') && store::getViewValue('page') == $i) {
                // not page 1 but we ARE on this page
                $active = 'active';
            } elseif (!store::getViewValue('page') && $i == 1) {
                $active = 'active';
            }
            $pages[] = '<a href="' . store::getCurrentUrl() . $param . '" class="dvbb-pagination-link ' . $active . '">' . $i .'</a>';
        }
        if (count($pages) > 1) {
            echo $pages = implode(' ', $pages);
        } else {
            echo $pages = '<a href="' . store::getCurrentUrl() . '" >1</a>';
        }
        ?>
    </div>
    <div class="dv-grid-column-12 dvbb-subnavigation-right">
        <?php 
        if (auth::can('create', 'forum', $forum->id)) {
            ?>
            <a href="<?=store::getRouter()->generate('topic-create', array('id' => $forum->id));?>">new topic</a>
            <?php 
        }
        ?>
    </div>
</nav>

<div class="dvbb-container">
    <div class="dvbb-container-header dvbb-forum-header"><?=$forum->title?></div>
    <div class="dvbb-container-legend dvbb-forum-legend dv-grid-row">
        <div class="dv-grid-column-1 dvbb-forum-legend-status">Read</div>
        <div class="dv-grid-column-14 dvbb-forum-legend-title">Thread / Author</div>
        <div class="dv-grid-column-2 dvbb-forum-legend-replies">Replies</div>
        <div class="dv-grid-column-7 dvbb-forum-legend-lastpost">Last Post</div>
    </div>
    <?php 
    // sticky topics
    if (count($stickyTopics) > 0) {
        ?>
        <div class="dvbb-container-legend dv-color-notice dvbb-forum-list-sticky">
            Sticky topics
        </div>
        <?php 
        foreach ($stickyTopics as $topic) {
            $unread = $topic->getUnreadStatus();
            
            $url = store::getRouter()->generate('topic', array('id' => $topic->id));
            $subPosts = count((new post())->getByCondition('parent_id = ?', $topic->id));
            $user = (new user())->getById($topic->user_id);
            ?>
            <div class="dvbb-container-row dv-grid-row dvbb-topic">
                <div class="dv-grid-column-1 dvbb-status">
                    <?php
                    $status = 'read'; 
                    if ($topic->closed) {
                        $status = 'closed';
                    } elseif ($unread) {
                        $status = 'unread';
                    }
                    ?>
                    <div class="dvbb-status-icon status-<?=$status;?>"></div>
                </div>
                <div class="dv-grid-column-14 dvbb-topic-title">
                    <a href="<?=$url;?>"><?=$topic->title;?></a><br />
                    <small style="color: grey"><?=$user->username;?> - posted <?=tool::getDateFormatted($topic->created_at)?></small>
                </div>
                <div class="dv-grid-column-2 dvbb-topic-replies"><?=$subPosts;?></div>
                <div class="dv-grid-column-7 dvbb-topic-lastpost"><?=tool::getDateFormatted($topic->last_post_at)?></div>
            </div>
            <?php
        }
    }
    // normal topics
    ?>
    <div class="dvbb-container-legend dv-color-notice dvbb-forum-list-normal">
        Normal topics
    </div>
    <?php 
    if (count($normalTopics) > 0) {
        foreach ($normalTopics as $topic) {
            $unread = $topic->getUnreadStatus();
            
            $url = store::getRouter()->generate('topic', array('id' => $topic->id));
            $subPosts = count((new post())->getByCondition('parent_id = ?', $topic->id));
            $user = (new user())->getById($topic->user_id);
            ?>
            <div class="dvbb-container-row dv-grid-row dvbb-topic">
                <div class="dv-grid-column-1 dvbb-status">
                    <?php
                    $status = 'read'; 
                    if ($topic->closed) {
                        $status = 'closed';
                    } elseif ($unread) {
                        $status = 'unread';
                    }
                    ?>
                    <div class="dvbb-status-icon status-<?=$status;?>"></div>
                </div>
                <div class="dv-grid-column-14 dvbb-topic-title">
                    <a href="<?=$url;?>"><?=$topic->title;?></a><br />
                    <small style="color: grey"><?=$user->username;?> - posted <?=tool::getDateFormatted($topic->created_at)?></small>
                </div>
                <div class="dv-grid-column-2 dvbb-topic-replies"><?=$subPosts;?></div>
                <div class="dv-grid-column-7 dvbb-topic-lastpost"><?=tool::getDateFormatted($topic->last_post_at)?></div>
            </div>
            <?php
        }
    } else {
        ?>
        <div class="dvbb-container-row dv-grid-row dvbb-forum-no-topics">
            No topics
        </div>
        <?php 
    }
    ?>
</div>

<nav class="dv-grid-row dvbb-subnavigation">
    <div class="dv-grid-column-12 dvbb-subnavigation-left">
        <?=$posts_per_page;?> topics per page: 
        <?=$pages;?>
    </div>
    <div class="dv-grid-column-12 dvbb-subnavigation-right">
        <?php 
        if (auth::can('create', 'forum', $forum->id)) {
            ?>
            <a href="<?=store::getRouter()->generate('topic-create', array('id' => $forum->id));?>">new topic</a>
            <?php 
        }
        ?>
    </div>
</nav>