<?php
$categories = (new category())->getAllSorted();
$lastPostPerForum = store::getViewValue('lastPostPerForum');

$categoriesShown = false;
$forumShown = false;

$posts_per_page = tool::getPostsPerPage();

foreach ($categories as $category) {

    // first check the user's rights
    if (auth::can('read', 'category', $category->id)) {
    
        $forums = (new forum())->getByCondition('category_id = ?', $category->id);
        
        $visibleForums = array();
        $forumsToShow = false;
        foreach ($forums as $forum) {
            if (auth::can('read', 'forum', $forum->id)) {
                $forumsToShow = true;
                $visibleForums[] = $forum;
            }
        }
        if ($forumsToShow) {
            ?>
            <div class="dvbb-container dvbb-category">
                <div class="dvbb-container-header dvbb-category-header"><?=$category->title?></div>
                <div class="dvbb-container-legend dvbb-category-legend dv-grid-row">
                    <div class="dv-grid-column-1 dvbb-category-legend-status">Read</div>
                    <div class="dv-grid-column-12 dvbb-category-legend-forum">Forum</div>
                    <div class="dv-grid-column-2 dvbb-category-legend-topics">Topics</div>
                    <div class="dv-grid-column-2 dvbb-category-legend-replies">Replies</div>
                    <div class="dv-grid-column-7 dvbb-category-legend-lastpost">Last Post</div>
                </div>
                <?php 
                foreach ($visibleForums as $forum) {
                    // build url to forum
                    $url = store::getRouter()->generate('forum', array('id' => $forum->id));
                    // only topics have a forum_id set
                    $topics = (new post())->getByCondition('forum_id = ?', $forum->id);
                    $topicCount = count($topics);
                    // replies have a parent_id instead of a forum_id
                    $replyCount = 0;
                    foreach ($topics as $topic) {
                        $replies = (new post())->getByCondition('parent_id = ?', $topic->id);
                        $replyCount = $replyCount + count($replies);
                    }
                    $lastPost = $lastPostPerForum[$forum->id];
                    if ($lastPost !== null) {
                        // get date & user of this lastPost
                        $user = (new user())->getById($lastPost->user_id);
                        
                        // get last reply, if any
                        $lastReply = $lastPost->getReplyLast();
                        if ($lastReply) {
                            $user = (new user())->getById($lastReply->user_id);
                        }
                    }
                    $unread = $forum->getUnreadStatus();
                    ?>
                    <div class="dvbb-container-row dvbb-forum dv-grid-row">
                        <div class="dv-grid-column-1 dvbb-status">
                            <?php
                            $status = 'read'; 
                            if ($unread) {
                                $status = 'unread';
                            }
                            ?>
                            <div class="dvbb-status-icon status-<?=$status;?>"></div>
                        </div>
                        <div class="dv-grid-column-12 dvbb-forum-title">
                            <a href="<?=$url;?>"><?=$forum->title;?></a><br />
                            <small style="color: grey"><?=$forum->description;?></small>
                        </div>
                        <div class="dv-grid-column-2 dvbb-forum-topics"><?=$topicCount;?></div>
                        <div class="dv-grid-column-2 dvbb-forum-replies"><?=$replyCount;?></div>
                        <div class="dv-grid-column-7 dvbb-forum-lastpost">
                            <?php 
                            if ($lastPost) {
                                $url = store::getRouter()->generate('topic', array('id' => $lastPost->id));
                                $anchorId = $lastPost->id;
                                $page = null;
                                if ($lastReply) {
                                    $anchorId = $lastReply->id;
                                    $page = $lastReply->getReplyPage();

                                    if (auth::getUser()) {
                                        $firstUnseen = $lastPost->getReplyFirstUnseen();

                                        if ($firstUnseen) {
                                            $anchorId = $firstUnseen->id;
                                            $page = $firstUnseen->getReplyPage();
                                        }
                                    }
                                }
                                if ($page) {
                                    $url .= '?page=' . $page;
                                }
                                ?>
                                <a href="<?=$url;?>#post-<?=$anchorId;?>" class="dvbb-forum-lastpost-link"><?=$lastPost->title;?></a><br />
                                <small style="color: grey"><?=$user->username?> at <?=tool::getDateFormatted($lastPost->last_post_at);?></small>
                                <?php 
                            } else {
                                echo '--';
                            }
                            ?>
                        </div>
                    </div>
                    <?php
                    $forumShown = true;
                }
                
                if (!$forumShown) {
                    ?>
                    <div class="dvbb-container-row dvbb-forum-no-forum dv-color-notice">
                        No forums
                    </div>
                    <?php 
                }
                ?>
            </div>
            <?php
            $categoriesShown = true;
        }
        
    }
}
if (!$categoriesShown) {
    ?>
    <div class="dvbb-container dvbb-container-row dvbb-forum-no-category dv-color-notice">
        No categories
    </div>
    <?php 
}

// get user statistics
$users = count((new user())->getAll());
// get post statistics
$posts = (new post())->getAll();
$topics = 0;
$replies = 0;
foreach ($posts as $post) {
    if ($post->forum_id) {
        $topics++;
    } else {
        $replies++;
    }
}
?>

<div class="dvbb-container dvbb-forum-stats">
    <div class="dvbb-container-header dvbb-forum-stats-header">Forum statistics</div>
    <div class="dvbb-container-row">
        <div class="dv-grid-row dvbb-forum-stats-member">
            <div class="dv-grid-column-4">Total members</div>
            <div class="dv-grid-column-4"><?=$users;?></div>
        </div>
        <div class="dv-grid-row dvbb-forum-stats-topic">
            <div class="dv-grid-column-4">Total topics</div>
            <div class="dv-grid-column-4"><?=$topics;?></div>
        </div>
        <div class="dv-grid-row dvbb-forum-stats-reply">
            <div class="dv-grid-column-4">Total replies</div>
            <div class="dv-grid-column-4"><?=$replies;?></div>
        </div>
    </div>
</div>