<?php 
$topic = store::getParam('topic');
?>

<nav class="dv-grid-row dvbb-subnavigation">
    <div class="dv-grid-column-12 dvbb-subnavigation-left">
        <?=store::getConfigParam('posts_per_page')?> posts per page: 
        <?php
        for ($i = 1; $i <= store::getParam('pageTotal'); $i++) {
            $param = '';
            if ($i > 1) {
                // only now do we actually add a parameter
                $param = '?page=' . $i;
            }
            // check if current page is 1 or otherwise
            $active = null;
            if (store::getParam('page') && store::getParam('page') == $i) {
                // not page 1 but we ARE on this page
                $active = 'active';
            } elseif (!store::getParam('page') && $i == 1) {
                $active = 'active';
            }
            $pages[] = '<a href="' . store::getCurrentUrl() . $param . '" class="dvbb-pagination-link ' . $active . '">' . $i .'</a>';
        }
        echo $pages = implode(' ', $pages);
        ?>
    </div>
    <div class="dv-grid-column-12 dvbb-subnavigation-right">
        <?php 
        if (auth::getUser()) {
            ?>
            <a href="<?=store::getRouter()->generate('reply-create', array('id' => $topic->id));?>">new reply</a>
            <?php 
        }
        ?>
    </div>
</nav>

<div class="dvbb-container">
    <div class="dvbb-container-header"><?=$topic->title?></div>
    <?php 
    $posts = store::getParam('posts');
    if (count($posts) > 0) {
        foreach ($posts as $subPost) {
            $user = (new user())->getById($subPost->user_id);
            ?>
            <div class="dvbb-container-row dv-grid-row">
                <div class="dv-grid-column-5">
                    <strong><?=$user->username?></strong>
                </div>
                <div class="dv-grid-column-19">
                    <span class="dv-color-notice">
                        <small>posted <?=$subPost->created_at?></small>
                    </span>
                    <?=tool::nl2p($subPost->body)?>
                </div>
            </div>
            <?php
        }
    }
    ?>
</div>

<nav class="dv-grid-row dvbb-subnavigation">
    <div class="dv-grid-column-12">
        <?=store::getConfigParam('posts_per_page')?> posts per page: 
        <?=$pages;?>
    </div>
    <div class="dv-grid-column-12 dvbb-subnavigation-right">
        <?php 
        if (auth::getUser()) {
            ?>
            <a href="<?=store::getRouter()->generate('reply-create', array('id' => $topic->id));?>">new reply</a>
            <?php 
        }
        ?>
    </div>
</nav>