<?php 
$topic = store::getViewValue('topic');
$posts_per_page = tool::getPostsPerPage();
?>

<nav class="dv-grid-row dvbb-subnavigation">
    <div class="dv-grid-column-12 dvbb-subnavigation-left">
        <?=$posts_per_page?> posts per page: 
        <?php
        for ($i = 1; $i <= store::getViewValue('pageTotal'); $i++) {
            $param = '';
            if ($i > 1) {
                // only now do we actually add a parameter
                $param = '?page=' . $i;
            }
            // check if current page is 1 or otherwise
            $active = null;
            if (store::getViewValue('page') && store::getViewValue('page') == $i) {
                // not page 1 but we ARE on this page
                $active = 'active';
            } elseif (!store::getViewValue('page') && $i == 1) {
                $active = 'active';
            }
            $pages[] = '<a href="' . store::getCurrentUrl() . $param . '" class="dvbb-pagination-link ' . $active . '">' . $i .'</a>';
        }
        echo $pages = implode(' ', $pages);
        ?>
    </div>
    <div class="dv-grid-column-12 dvbb-subnavigation-right">
        <?php 
        if ($topic->closed) {
            ?>
            <div class="dvbb-topic-closed">Topic is closed</div>
            <?php 
        } else {
            if (auth::can('create', 'forum', $topic->forum_id)) {
                ?>
                <a href="<?=store::getRouter()->generate('reply-create', array('id' => $topic->id));?>">new reply</a>
                <?php
            } 
        }
        ?>
    </div>
</nav>

<div class="dvbb-container">
    <div class="dvbb-container-header"><?=$topic->title?></div>
    <?php 
    $posts = store::getViewValue('posts');
    if (count($posts) > 0) {
        foreach ($posts as $subPost) {
            $user = (new user())->getById($subPost->user_id);
            $userGroup = $user->getGroup();
            $userSubGroup = $user->getSubGroup();
            $avatar = $user->getAvatar();
            if ($user->id) {
                $settings = $user->getSettings();
            } else {
                $settings = array();
            }
            ?>
            <a name="post-<?=$subPost->id;?>"></a>
            <div class="dvbb-container-row dv-grid-row dvbb-post">
                <div class="dv-grid-column-5 dvbb-post-user">
                    <div>
                        <div class="dvbb-user-name"><?=$user->username?></div>
                        <div class="dvbb-user-group"><?=$userGroup->title?></div>
                        <?php 
                        if ($userSubGroup) {
                            ?>
                            <div class="dvbb-user-group-sub"><?=$userSubGroup->title;?></div>
                            <?php 
                        }
                        ?>
                        <?php 
                        $src = tool::getBase64ImageSrc($avatar);
                        if ($src) {
                            ?>
                            <div class="dvbb-user-avatar">
                                <img src="<?=$src;?>" />
                            </div>
                            <?php 
                        }
                        ?>
                    </div>
                    <div class="dvbb-user-info">
                        <?php 
                        if (isset($settings['location'])) {
                            if (!isset($settings['location_visible']) || $settings['location_visible']->value) {
                                ?>
                                Location: <?=$settings['location']->value;?>
                                <?php 
                            }
                        }
                        ?>
                    </div>
                    <div class="dvbb-user-links">
                        <?php
                        // show some links to logged in users and only if a user has an id
                        if (auth::getUser() && $user->id) {
                            ?>
                            <a href="<?=store::getRouter()->generate('user-profile', array('id' => $user->id));?>">profile</a><br />
                            <?php 
                        }
                        ?>
                    </div>
                </div>
                <div class="dv-grid-column-19 dvbb-post-content">
                    <div class="dvbb-post-content-created">
                        posted <?=tool::getDateFormatted($subPost->created_at)?>
                    </div>
                    
                    <div class="dvbb-post-content-body">
                        <?=tool::nl2p(tool::fromBB($subPost->body));?>
                    </div>
                    
                    <?php 
                    // look for updates
                    $updated = null;
                    $updateUser = null;
                    if ($subPost->updated_user_id) {
                        $updateUser = (new user())->getById($subPost->updated_user_id);
                    }
                    if ($subPost->created_at !== $subPost->updated_at) {
                        $updated = 'updated ' . tool::getDateFormatted($subPost->updated_at);
                        if ($updateUser) {
                            // admins do silent edits, always
                            if ($updateUser->group_id == 1) {
                                $updated = null;
                            } else {
                                $updated .= ' by ' . $updateUser->username;
                            }
                        }
                    }
                    if ($updated) {
                        ?>
                        <div class="dvbb-post-content-updated"><?=$updated;?></div>
                        <?php 
                    }
                    ?>
                </div>
            </div>
            
            <?php 
            // user must be able to at least update or create in this forum for this bar to make any sense
            if (
                auth::can('create', 'forum', $topic->forum_id)
                || auth::can('update', 'forum', $topic->forum_id)
                || auth::can('update', 'forum', $topic->forum_id)
                || auth::can('admin')
            ) {
                ?>
                <div class="dvbb-container-row dv-grid-row">
                    <div class="dv-grid-column-5"></div>
                    <?php 
                    // if the user has a signature, show it
                    if (isset($settings['signature'])) {
                        ?>
                        <div class="dv-grid-column-19 dvbb-user-signature">
                            <?=nl2br(tool::fromBB($settings['signature']->value));?>
                        </div>
                        <?php 
                    }
                    ?>
                </div>
                <div class="dvbb-container-row dv-grid-row dvbb-post-actions">
                    <div class="dv-grid-column-5"></div>
                    <?php 
                    // If the user can create here, they're allowed to quote
                    $canQuote = auth::can('create', 'forum', $topic->forum_id);
                    // If the user can update in here and this post belongs to the user, allow user edit
                    $canUpdateOwn = (auth::can('update', 'forum', $topic->forum_id) && auth::getUser()->id === $subPost->user_id);
                    // If the user can mod, allow mod options, allow mod edit and delete
                    $canMod = auth::can('mod', 'forum', $topic->forum_id);
                    ?>
                    
                    <div class="dv-grid-column-9 dvbb-post-actions-left">
                        <?php 
                        if ($canQuote) {
                            ?>
                            <a href="<?=store::getRouter()->generate('reply-create-quote', array('id' => $topic->id, 'quoteId' => $subPost->id));?>">quote post</a>
                            <?php
                        }
                        if ($canUpdateOwn || $canMod) {
                            ?>
                            - <a href="<?=store::getRouter()->generate('reply-update', array('id' => $subPost->id));?>">edit post</a> <?=($canMod && !$canUpdateOwn? '(as mod)': '');?>
                            <?php 
                        }
                        ?>
                    </div>
                    
                    <?php 
                    if ($canMod) {
                        $isTopic = ($topic->id === $subPost->id);
                        ?>
                        <div class="dv-grid-column-10 dvbb-post-actions-right">
                            moderate: 
                            <a href="<?=store::getRouter()->generate('mod-reply-delete', array('id' => $subPost->id));?>">delete <?=($isTopic ? 'topic':'post');?></a>
                        </div>
                        <?php 
                    }
                    ?>
                </div>
                <?php
            } 
        }
    }
    ?>
</div>
<?php 
$currentUrl = store::getCurrentUrl();
if (store::getViewValue('page')) {
    $currentUrl = store::getCurrentUrl() . '?page=' . store::getViewValue('page');
}
if (auth::can('create', 'forum', $topic->forum_id)) {
    ?>
    <form method="post" action="<?=$currentUrl;?>">
        <div class="dvbb-container dvbb-topic-reply">
            <div class="dvbb-container-header dvbb-topic-reply-header">Post new reply as <?=auth::getUser()->username;?></div>
            <div class="dvbb-container-row dvbb-topic-reply-form">
    
                <?php 
                if ($topic->closed) {
                    ?>
                    <span class="dv-color-notice">Topic is closed</span>
                    <?php 
                } else {
                    echo tool::partial('general/partial/reply.phtml');
                }
                ?>
                
            </div>
        </div>
    </form>
    <?php 
}
?>

<?php 
if (auth::can('mod', 'forum', $topic->forum_id)) {
    $ajaxUrl = store::getRouter()->generate('ajax-topic-sticky', array('id' => $topic->id));
    $ajaxRedirect = store::getRouter()->generate('forum', array('id' => $topic->forum_id));
    ?>
    <div class="dvbb-container dvbb-mod-topic">
        <div class="dvbb-container-row">
            <div class="dv-align-right">
                moderator options: 
                <a href="<?=store::getRouter()->generate('mod-topic-close', array('id' => $topic->id));?>"><?=($topic->closed ? 'open' : 'close');?> topic</a> - 
                <a href="<?=store::getRouter()->generate('mod-topic-delete', array('id' => $topic->id));?>">delete topic</a> - 
                <a href="#" data-ajax-url="<?=$ajaxUrl;?>" data-ajax-redirect="<?=$ajaxRedirect;?>"><?=($topic->sticky ? 'un' : '');?>sticky topic</a>
            </div>
        </div>
    </div>
    <?php 
}
?>

<nav class="dv-grid-row dvbb-subnavigation">
    <div class="dv-grid-column-12 dvbb-subnavigation-left">
        <?=$posts_per_page?> posts per page: 
        <?=$pages;?>
    </div>
    <div class="dv-grid-column-12 dvbb-subnavigation-right">
        <?php 
        if ($topic->closed) {
            ?>
            <span class="dv-color-notice">Topic is closed</span>
            <?php 
        } else {
            if (auth::can('create', 'forum', $topic->forum_id)) {
                ?>
                <a href="<?=store::getRouter()->generate('reply-create', array('id' => $topic->id));?>">new reply</a>
                <?php
            } 
        }
        ?>
    </div>
</nav>