<nav class="dv-grid-row sub-navigation">
    <div class="dv-grid-column-12">
        <?=app::getConfigKey('posts_per_page')?> posts per page: 
        <?php
        for ($i = 1; $i <= app::getViewParam('pageTotal'); $i++) {
            $param = '';
            if ($i > 1) {
                // only now do we actually add a parameter
                $param = '?page=' . $i;
            }
            // check if current page is 1 or otherwise
            $active = null;
            if (app::getViewParam('page') && app::getViewParam('page') == $i) {
                // not page 1 but we ARE on this page
                $active = 'active';
            } elseif (!app::getViewParam('page') && $i == 1) {
                $active = 'active';
            }
            $pages[] = '<a href="' . app::getCurrentUrl() . $param . '" class="' . $active . '">' . $i .'</a>';
        }
        echo $pages = implode(' ', $pages);
        ?>
    </div>
    <div class="dv-grid-column-12 dv-align-right">
        <a href="<?=app::getUrl();?>">new reply</a>
    </div>
</nav>

<?php 
$topic = app::getViewParam('topic');
?>
<div class="dvbb-forum-container">
    <strong class="dvbb-category-title"><?=$topic->title?></strong>
    <?php 
    $posts = app::getViewParam('posts');
    if (count($posts) > 0) {
        foreach ($posts as $subPost) {
            $user = (new user())->getById($subPost->user_id);
            ?>
            <div class="dvbb-forum dv-grid-row">
                <div class="dv-grid-column-5">
                    <strong><?=$user->username?></strong>
                </div>
                <div class="dv-grid-column-19">
                    <span class="dv-color-notice">
                        <?=$subPost->title?> <small><?=$subPost->created_at?></small>
                    </span>
                    <p>
                        <?=$subPost->body?>
                    </p>
                </div>
            </div>
            <?php
        }
    }
    ?>
</div>
<br />
<nav class="dv-grid-row sub-navigation">
    <div class="dv-grid-column-12">
        <?=app::getConfigKey('posts_per_page')?> posts per page: 
        <?=$pages;?>
    </div>
    <div class="dv-grid-column-12 dv-align-right">
        <a href="<?=app::getUrl();?>">new reply</a>
    </div>
</nav>