<?php 
$active = array(
    'admin' => false,
    'admin-forums' => false,
    'admin-users' => false,
    'admin-usergroups' => false,
    'admin-maintenance' => false,
);

$active[store::getViewValue('active')] = true;
?>
<div class="dvbb-container">
    <div class="dvbb-container-row dv-align-center">
        <a href="<?=store::getRouter()->generate('admin')?>" class="dv-form-button <?=($active['admin']?'':'inactive');?>">Index</a>
        <a href="<?=store::getRouter()->generate('admin-forums')?>" class="dv-form-button <?=($active['admin-forums']?'':'inactive');?>">Categories & forums</a>
        <a href="<?=store::getRouter()->generate('admin-users')?>" class="dv-form-button <?=($active['admin-users']?'':'inactive');?>">Users</a>
        <a href="<?=store::getRouter()->generate('admin-usergroups')?>" class="dv-form-button <?=($active['admin-usergroups']?'':'inactive');?>">Usergroups</a>
        <!-- a href="<?=store::getRouter()->generate('admin-maintenance')?>" class="dv-form-button <?=($active['admin-maintenance']?'':'inactive');?>">Maintenance</a -->
    </div>
</div>

<?php 
if (store::getViewValue('success')) {
    ?>
    <div class="dvbb-container dvbb-container-row dv-notification-message dv-background-correct dv-color-white">
        Your settings have been saved.
    </div>
    <?php 
}
