<?php 
$title = null;
$body = null;
if(store::getPostValues()) {
    $title = store::getPostValue('title');
    $body = store::getPostValue('body');
}
if(store::getViewValue('error')) {
    ?>
    <div class="dvbb-container dvbb-container-row dv-notification-message dv-background-alert dv-color-white">
        <?=store::getViewValue('error');?>
    </div> 
    <?php 
}
?>

<form method="post" action="<?=store::getCurrentUrl()?>" class="dvbb-form">
    <div class="dvbb-container">
        <div class="dvbb-container-header">New topic in <?=store::getViewValue('forum')->title;?></div>
        <div class="dvbb-container-row">
        
            <div class="dv-grid-row">
                <label class="dv-grid-column-8 dv-form-label">Topic title</label>
                <div class="dv-grid-column-16"><input type="text" name="title" class="dv-form-element" value="<?=$title?>" /></div>
            </div>
            <div class="dv-grid-row">
                <label class="dv-grid-column-8 dv-form-label">Topic content</label>
                <div class="dv-grid-column-16"><textarea name="body" class="dv-form-element"><?=$body;?></textarea></div>
            </div>
        
        </div>
    </div>
    <div class="dvbb-container">
        <div class="dvbb-container-row dv-align-center">
        
            <input type="submit" name="post" value="post" class="dv-form-button" />
        
        </div>
    </div>
</form>