<?php 
$title = null;
$body = null;
if(!empty($_POST)) {
    var_dump($_POST);
    $title = $_POST['title'];
    $body = $_POST['body'];
}
?>

    <div class="dvbb-container">
        <div class="dvbb-container-header">New topic</div>
        <div class="dvbb-container-row">
        
            <form method="post" action="<?=app::getCurrentUrl()?>" class="dvbb-form">
                <div class="dv-grid-row">
                    <label class="dv-grid-column-8 dv-form-label">Topic title</label>
                    <div class="dv-grid-column-16"><input type="text" name="title" class="dv-form-element" value="<?=$title?>" /></div>
                </div>
                <div class="dv-grid-row">
                    <label class="dv-grid-column-8 dv-form-label">Topic content</label>
                    <div class="dv-grid-column-16"><textarea name="body" class="dv-form-element"><?=$body;?></textarea></div>
                </div>
                <div class="dv-grid-row">
                    <label class="dv-grid-column-8 dv-form-label"></label>
                    <div class="dv-grid-column-16">
                        <input type="submit" name="post" value="post" class="dv-form-button" />
                        <input type="submit" name="preview" value="preview" class="dv-form-button" />
                </div>
            </form>
        
        </div>
    </div>
