<?php 
$title = null;
$body = null;
if(store::getPostValues()) {
    $title = store::getPostValue('title');
    $body = store::getPostValue('body');
}
if(store::getViewValue('errors')) {
    ?>
    <div class="dvbb-container dvbb-container-row dv-notification-message dv-background-alert dv-color-white">
        <?=store::getViewValue('errors');?>
    </div> 
    <?php 
}
?>

<form method="post" action="<?=store::getCurrentUrl()?>" class="dvbb-form">
    <div class="dvbb-container dvbb-topic-create">
        <div class="dvbb-container-header dvbb-topic-create-header">New topic in <?=store::getViewValue('forum')->title;?></div>
        <div class="dvbb-container-row dvbb-topic-create-form">
        
            <div class="dv-grid-row">
                <label class="dv-grid-column-8 dvbb-form-label">Topic title</label>
                <div class="dv-grid-column-16"><input type="text" name="title" class="dv-form-element" value="<?=$title?>" /></div>
            </div>
            <div class="dv-grid-row">
                <label class="dv-grid-column-8 dvbb-form-label">Topic content</label>
                <div class="dv-grid-column-16">
                
                    <div class="dvbb-container-row dvbb-bbcode-buttons">
                        <a href="#" class="dv-form-button" data-bbcode-tag="b" data-bbcode-target=".dvbb-topic-textarea" title="Bold">
                            <i class="fa fa-fw fa-bold"></i>
                        </a>
                        <a href="#" class="dv-form-button" data-bbcode-tag="i" data-bbcode-target=".dvbb-topic-textarea" title="Italic">
                            <i class="fa fa-fw fa-italic"></i>
                        </a>
                        <a href="#" class="dv-form-button" data-bbcode-tag="u" data-bbcode-target=".dvbb-topic-textarea" title="Underline">
                            <i class="fa fa-fw fa-underline"></i>
                        </a>
                        <a href="#" class="dv-form-button" data-bbcode-tag="s" data-bbcode-target=".dvbb-topic-textarea" title="Strikethrough">
                            <i class="fa fa-fw fa-strikethrough"></i>
                        </a>
                        <a href="#" class="dv-form-button" data-bbcode-tag="color" data-bbcode-target=".dvbb-topic-textarea" title="Color">
                            <i class="fa fa-fw fa-eyedropper"></i>
                        </a>
                        
                        &nbsp; &nbsp; 
                        
                        <a href="#" class="dv-form-button" data-bbcode-tag="left" data-bbcode-target=".dvbb-topic-textarea" title="Align left">
                            <i class="fa fa-fw fa-align-left"></i>
                        </a>
                        <a href="#" class="dv-form-button" data-bbcode-tag="center" data-bbcode-target=".dvbb-topic-textarea" title="Align center">
                            <i class="fa fa-fw fa-align-center"></i>
                        </a>
                        <a href="#" class="dv-form-button" data-bbcode-tag="right" data-bbcode-target=".dvbb-topic-textarea" title="Align right">
                            <i class="fa fa-fw fa-align-right"></i>
                        </a>
                        <a href="#" class="dv-form-button" data-bbcode-tag="justify" data-bbcode-target=".dvbb-topic-textarea" title="Align justify">
                            <i class="fa fa-fw fa-align-justify"></i>
                        </a>
                        
                        &nbsp; &nbsp; 
                        
                        <a href="#" class="dv-form-button" data-bbcode-tag="quote" data-bbcode-target=".dvbb-topic-textarea" title="Quote">
                            <i class="fa fa-fw fa-quote-right"></i>
                        </a>
                        <a href="#" class="dv-form-button" data-bbcode-tag="code" data-bbcode-target=".dvbb-topic-textarea" title="Code">
                            <i class="fa fa-fw fa-code"></i>
                        </a>
                        
                        &nbsp; &nbsp; 
                        
                        <a href="#" class="dv-form-button" data-bbcode-tag="url" data-bbcode-target=".dvbb-topic-textarea" title="Link">
                            <i class="fa fa-fw fa-link"></i>
                        </a>
                        <a href="#" class="dv-form-button" data-bbcode-tag="img" data-bbcode-target=".dvbb-topic-textarea" title="Image">
                            <i class="fa fa-fw fa-image"></i>
                        </a>
                        <a href="#" class="dv-form-button" data-bbcode-tag="video" data-bbcode-target=".dvbb-topic-textarea" title="Video">
                            <i class="fa fa-fw fa-youtube"></i>
                        </a>
                    </div>
                    <textarea name="body" class="dvbb-topic-textarea dv-form-element"><?=$body;?></textarea>
                </div>
            </div>
        
        </div>
    </div>
    <div class="dvbb-container">
        <div class="dvbb-container-row dv-align-center">
        
            <input type="submit" name="post" value="post" class="dv-form-button" />
        
        </div>
    </div>
</form>