<?php 
$topic = store::getViewValue('topic');
?>

<div class="dvbb-container">
    <div class="dvbb-container-header">Delete topic '<?=$topic->title;?>'</div>
    <div class="dvbb-container-row dv-grid-row">
        <p>
            Are you sure you want to delete this topic and all replies to it?
        </p>
        <p class="dv-color-alert">
            This cannot be undone!
        </p>
    </div>
</div>

<form method="post" action="<?=store::getCurrentUrl()?>" class="dvbb-form">
    <div class="dvbb-container">
        <div class="dvbb-container-row dv-align-center">
        
            <input type="submit" name="post" value="delete topic" class="dv-form-button dv-background-alert" />
        
        </div>
    </div>
</form>