<!doctype html>

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        
        <title>dvbb prototype</title>
        
        <link rel="stylesheet" type="text/css" media="all"  href="<?=dvbb::getUrl();?>/public/css/lib/normalize.css" />
        <link rel="stylesheet" type="text/css" media="all"  href="<?=dvbb::getUrl();?>/public/css/lib/dv-import.css" />
        <link rel="stylesheet" type="text/css" media="all"  href="<?=dvbb::getUrl();?>/public/css/common.css" />
        <link rel="stylesheet" type="text/css" media="all"  href="<?=dvbb::getUrl();?>/public/css/default-theme.css" />
        
        <script src="<?=dvbb::getUrl();?>/public/js/lib/jquery-1.11.2.min.js"></script>
        <script src="<?=dvbb::getUrl();?>/public/js/lib/html5shiv.js"></script>
        <script src="<?=dvbb::getUrl();?>/public/js/common.js"></script>
        
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    </head>
    
    <body class="dv-width-site dv-margin-auto">