
    <div class="dvbb-container dvbb-maintenance">
        <div class="dvbb-container-header dvbb-maintenance-header">This forum is in maintenance mode</div>
        <div class="dvbb-container-row dvbb-maintenance-content">
            <p>
                This forum is currently unavailable as maintenance mode has been turned on. This is usually done to prevent
                any changes to the database while maintenance is underway.
            </p>
        </div>
    </div>