<?php 
$body = null;
if(app::getPost()) {
    $body = app::getPostByKey('body');
}
if(app::getViewByKey('error')) {
    ?>
    <div class="dvbb-container dvbb-container-row dv-notification-message dv-background-alert dv-color-white">
        <?=app::getViewByKey('error');?>
    </div> 
    <?php 
}
?>

<form method="post" action="<?=app::getCurrentUrl()?>" class="dvbb-form">
    <div class="dvbb-container">
        <div class="dvbb-container-header">New reply to <?=app::getViewByKey('topic')->title;?></div>
        <div class="dvbb-container-row">
        
            <div class="dv-grid-row">
                <label class="dv-grid-column-8 dv-form-label">Reply content</label>
                <div class="dv-grid-column-16"><textarea name="body" class="dv-form-element"><?=$body;?></textarea></div>
            </div>
        
        </div>
    </div>
    <div class="dvbb-container">
        <div class="dvbb-container-row dv-align-center">
        
            <input type="submit" name="post" value="post" class="dv-form-button" />
        
        </div>
    </div>
</form>