<?php 
$body = null;
if(store::getPostValues()) {
    $body = store::getPostValue('body');
}
if(store::getViewValue('errors')) {
    ?>
    <div class="dvbb-container dvbb-container-row dv-notification-message dv-background-alert dv-color-white dvbb-errors">
        <?=store::getViewValue('errors');?>
    </div> 
    <?php 
}
?>

<form method="post" action="<?=store::getCurrentUrl()?>" class="dvbb-form">
    <div class="dvbb-container dvbb-topic-reply">
        <div class="dvbb-container-header dvbb-topic-reply-header">New reply to <?=store::getViewValue('topic')->title;?></div>
        <div class="dvbb-container-row dvbb-topic-reply-form">
        
            <?=tool::partial('general/partial/reply.phtml')?>
        
        </div>
    </div>
</form>