<?=tool::partial('admin/partial/nav.phtml')?>

<?php 
$forum = store::getViewValue('forum');
?>

<div class="dvbb-container">
    <div class="dvbb-container-header">Delete forum '<?=$forum->title;?>'</div>
    <div class="dvbb-container-row">
        <p>
            If you delete this forum, all topics within this forum will be deleted as well! This cannot be undone!
        </p>
    </div>
</div>
<form method="post" action="<?=store::getCurrentUrl();?>">
    <div class="dvbb-container">
        <div class="dvbb-container-row dv-align-center">
        
            <input type="submit" name="post" value="delete" class="dv-form-button dv-background-alert" />
        
        </div>
    </div>
</form>