<?=tool::partial('admin/partial/nav.phtml')?>

<div class="dvbb-container">
    <div class="dvbb-container-header">Categories & forums</div>
    <div class="dvbb-container-row">
        <p>
            Here you can add, edit or delete categories & forums. You can also change the order of categories & forums
            by changing the order numbers and clicking 'save order' at the bottom.
        </p>
        <p>
            Note: If you delete anything here, everything connected to it will be removed as well! If you remove a
            forum, its posts will be deleted, and if you delete a category, its forums and their posts will be deleted
            as well. Keep this in mind, and move over any forums or posts you wish to save.
        </p>
    </div>
</div>

<form method="post" action="<?=store::getCurrentUrl();?>">
    <div class="dvbb-container">
        <div class="dvbb-container-header">Manage categories & forums</div>
        <div class="dvbb-container-row">
            <p>
            
                <div class="dvbb-container dvbb-container-row dvbb-navigation">
                    <?=store::getConfigValue('name')?>
                    <span class="dv-float-right">
                        <a href="<?=store::getRouter()->generate('admin-category-create')?>">add category</a>
                    </span>
                </div>
                <?php 
                $categories = (new category())->getAllSorted();
                foreach ($categories as $category) {
                    ?>
                    <div class="dvbb-container dvbb-container-row dvbb-navigation" style="margin-left: 2rem;">
                        <?=$category->title;?>
                        <span class="dv-float-right">
                            <a href="<?=store::getRouter()->generate('admin-forum-create', array('id' => $category->id))?>">add forum</a> - 
                            <a href="<?=store::getRouter()->generate('admin-category-update', array('id' => $category->id))?>">edit</a> - 
                            <a href="<?=store::getRouter()->generate('admin-category-delete', array('id' => $category->id))?>">delete</a> - 
                            <input type="input" name="category[<?=$category->id?>]" class="dv-align-center" style="margin-top:-0.5rem;width:2rem;color: #000;" value="<?=$category->sort?>" />
                        </span>
                    </div>
                    <?php 
                    $forums = (new forum())->getByQuery((new query())->where('category_id = ?', $category->id)->orderBy('sort', 'ASC'));
                    foreach ($forums as $forum) {
                        ?>
                        <div class="dvbb-container dvbb-container-row" style="margin-left: 4rem;">
                            <?=$forum->title;?>
                            <span class="dv-float-right">
                                <a href="<?=store::getRouter()->generate('admin-forum-update', array('id' => $forum->id))?>">edit</a> - 
                                <a href="<?=store::getRouter()->generate('admin-forum-delete', array('id' => $forum->id))?>">delete</a> - 
                                <input type="input" name="forum[<?=$forum->id?>]" class="dv-align-center" style="margin-top:-0.5rem;width:2rem;color: #000;" value="<?=$forum->sort?>" />
                            </span>
                            <div><small class="dv-color-notice"><?=$forum->description?></small></div>
                        </div>
                        <?php 
                    }
                }
                ?>
                
            </p>
        </div>
    </div>

    <div class="dvbb-container">
        <div class="dvbb-container-row dv-align-center">
        
            <input type="submit" name="post" value="save order" class="dv-form-button" />
        
        </div>
    </div>
</form>