<?=tool::partial('admin/partial/nav.phtml')?>

<div class="dvbb-container">
    <div class="dvbb-container-header">Admin index</div>
    <div class="dvbb-container-row">
        <p>
            You can use the admin system to change all relevant parts of the forum. Below you can see the currently
            loaded config files.
        </p>
    </div>
</div>

<div class="dvbb-container">
    <div class="dvbb-container-header">config.ini</div>
    <div class="dvbb-container-row">
        <?php 
        $configContents = file_get_contents(store::getPath() . '/application/config/config.ini');
        ?>
        <pre class="dvbb-code"><?=$configContents;?></pre>
    </div>
</div>


<?php
if (file_exists(store::getPath() . '/application/config/custom.ini')) {
    $configContents = file_get_contents(store::getPath() . '/application/config/custom.ini');
    ?>
    <div class="dvbb-container">
        <div class="dvbb-container-header">custom.ini</div>
        <div class="dvbb-container-row">
            <pre class="dvbb-code"><?=$configContents;?></pre>
        </div>
    </div>
    <?php 
}
?>
