<?=tool::partial('admin/partial/nav.phtml')?>

<div class="dvbb-container">
    <div class="dvbb-container-header">Maintenance</div>
    <div class="dvbb-container-row">
        <p>
            introduction
        </p>
    </div>
</div>

<div class="dvbb-container">
    <div class="dvbb-container-header">Manage existing</div>
    <div class="dvbb-container-row">
        <p>
        
            whoot
            
        </p>
    </div>
</div>