<!doctype html>

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        
        <title>dv-template v0.2</title>
        
        <link rel="stylesheet" type="text/css" media="all"  href="./css/lib/normalize.css" />
        <link rel="stylesheet" type="text/css" media="all"  href="./css/lib/dv-import.css" />
        <link rel="stylesheet" type="text/css" media="all"  href="./css/common.css" />
        
        <script src="./js/lib/jquery-1.11.2.min.js"></script>
        <script src="./js/lib/html5shiv.js"></script>
        <script src="./js/common.js"></script>
        
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
        
        <style>
            /* this is purely for this demonstration page */
            [class*='dv-grid-column-'] {
                border: 1px solid #888;
                font-size: 0.8rem;
                color: #333;
            }
            section > article {
                margin-bottom: 2em;
            }
            .color-box {
                display: inline-block;
                width: 2em;
                height: 2em;
            }
        </style>
    </head>
    
    <body class="dv-width-site dv-margin-auto">
    
        <header>
            <h1>dv-template v0.2</h1>
        </header>

        <section>

            <article>
                <h2>Welcome to the demonstration page</h2>
                <p>
                    The most important things about dv-template will be shortly demonstrated here.
                </p>
            </article>
            
            <article>
                <h3>1. Grid system (dv-grid.css)</h3>
                <p>
                    The grid system is divided into 24 columns, to allow fine-grained control over placement and size.
                    It also nests nicely and breaks on mobile devices.
                </p>
                <p>
                    <div class="dv-grid-row">
                        <div class="dv-grid-column-24">.dv-grid-column-24</div>
                    </div>
                    <div class="dv-grid-row">
                        <div class="dv-grid-column-8">.dv-grid-column-8</div>
                        <div class="dv-grid-column-8">.dv-grid-column-8</div>
                        <div class="dv-grid-column-8">.dv-grid-column-8</div>
                    </div>
                    <div class="dv-grid-row">
                        <div class="dv-grid-column-4">.dv-grid-column-4</div>
                        <div class="dv-grid-column-16">
                        
                            <div class="dv-grid-row">
                                <div class="dv-grid-column-4">.dv-grid-column-4</div>
                                <div class="dv-grid-column-16">.dv-grid-column-16</div>
                                <div class="dv-grid-column-4">.dv-grid-column-4</div>
                            </div>
                        
                        </div>
                        <div class="dv-grid-column-4">.dv-grid-column-4</div>
                    </div>
                </p>
            </article>

            <article>
                <h3>2. Classes (dv-classes.css)</h3>
                <p>
                    dv-classes.css contains utility classes used for positioning, sizing, visibility, text styling, etc.
                </p>
                <p>
                    <div class="dv-text-bold">.dv-text-bold</div>
                    <div class="dv-text-italic">.dv-text-italic</div>
                    <div class="dv-text-underline">.dv-text-underline</div>
                    <div class="dv-text-overline">.dv-text-overline</div>
                    <div class="dv-text-strike">.dv-text-strike</div>
                </p>

                <p>
                    <div class="dv-align-left dv-debug-border">.dv-align-left</div>
                    <div class="dv-align-center dv-debug-border">.dv-align-center</div>
                    <div class="dv-align-right dv-debug-border">.dv-align-right</div>
                </p>
                <p>
                    <div class="dv-float-left dv-debug-border">.dv-float-left</div>
                    <div class="dv-float-right dv-debug-border">.dv-float-right</div>
                    <br class="dv-clear" />
                </p>
            </article>

            <article>
                <h3>3. Colors (dv-colors.css)</h3>
                <p>
                    dv-colors contains specifically chosen colors that work well together, as well as often-used brand
                    colors and a notification container to be used in conjunction with the status colors.
                </p>
                <p>
                    <h4>Status colors</h4>
                    <div class="color-box dv-background-notice" title=".dv-background-notice"></div>
                    <div class="color-box dv-background-correct" title=".dv-background-correct"></div>
                    <div class="color-box dv-background-warning" title=".dv-background-warning"></div>
                    <div class="color-box dv-background-alert" title=".dv-background-alert"></div>
                </p>
                <p>
                    <div class="dv-color-notice">.dv-color-notice</div>
                    <div class="dv-color-correct">.dv-color-correct</div>
                    <div class="dv-color-warning">.dv-color-warning</div>
                    <div class="dv-color-alert">.dv-color-alert</div>
                </p>
                <p>
                    <h4>Status notifications</h4>
                    Adding 'closable' to a .dv-notification will add a Font Awesome times-icon. Simply handle the click
                    to implement it.
                </p>
                <p>
                    <div class="dv-notification dv-background-notice closable">.dv-background-notice</div>
                    <div class="dv-notification dv-background-correct">.dv-background-correct</div>
                    <div class="dv-notification dv-background-warning">.dv-background-warning</div>
                    <div class="dv-notification dv-background-alert">.dv-background-alert</div>
                </p>
                <p>
                    <h4>Default colors</h4>
                    <div class="color-box dv-background-white" title=".dv-background-white"></div>
                    <div class="color-box dv-background-grey-light" title=".dv-background-grey-light"></div>
                    <div class="color-box dv-background-grey" title=".dv-background-grey"></div>
                    <div class="color-box dv-background-grey-dark" title=".dv-background-grey-dark"></div>
                    <div class="color-box dv-background-grey-darker" title=".dv-background-grey-darker"></div>
                    <div class="color-box dv-background-black" title=".dv-background-black"></div>
                    
                    <div class="color-box dv-background-red-light" title=".dv-background-red-light"></div>
                    <div class="color-box dv-background-red" title=".dv-background-red"></div>
                    <div class="color-box dv-background-red-dark" title=".dv-background-red-dark"></div>
                    
                    <div class="color-box dv-background-green-light" title=".dv-background-green-light"></div>
                    <div class="color-box dv-background-green" title=".dv-background-green"></div>
                    <div class="color-box dv-background-green-dark" title=".dv-background-green-dark"></div>
                    
                    <div class="color-box dv-background-blue-light" title=".dv-background-blue-light"></div>
                    <div class="color-box dv-background-blue" title=".dv-background-blue"></div>
                    <div class="color-box dv-background-blue-dark" title=".dv-background-blue-dark"></div>
                    
                    <div class="color-box dv-background-orange-light" title=".dv-background-orange-light"></div>
                    <div class="color-box dv-background-orange" title=".dv-background-orange"></div>
                    <div class="color-box dv-background-orange-dark" title=".dv-background-orange-dark"></div>
                    
                    <div class="color-box dv-background-yellow-light" title=".dv-background-yellow-light"></div>
                    <div class="color-box dv-background-yellow" title=".dv-background-yellow"></div>
                    <div class="color-box dv-background-yellow-dark" title=".dv-background-yellow-dark"></div>
                </p>
                <p>
                    <h4>Brand colors</h4>
                    <div class="color-box dv-background-brand-devvoh" title=".dv-background-brand-devvoh"></div>
                    <div class="color-box dv-background-brand-twitter" title=".dv-background-brand-twitter"></div>
                    <div class="color-box dv-background-brand-linkedin" title=".dv-background-brand-linkedin"></div>
                    <div class="color-box dv-background-brand-facebook" title=".dv-background-brand-facebook"></div>
                    <div class="color-box dv-background-brand-googleplus" title=".dv-background-brand-googleplus"></div>
                    <div class="color-box dv-background-brand-instagram" title=".dv-background-brand-instagram"></div>
                    <div class="color-box dv-background-brand-youtube" title=".dv-background-brand-youtube"></div>
                </p>
            </article>
            
            <article>
                <h3>Forms (dv-forms.css)</h3>
                <p>
                    Default form styling.
                </p>
                <p>
                    <input type="text" class="dv-form-element" />
                    <input type="button" value="default" class="dv-form-button" />
                    <input type="button" value="notice" class="dv-form-button dv-background-notice" />
                    <input type="button" value="correct" class="dv-form-button dv-background-correct" />
                    <input type="button" value="warning" class="dv-form-button dv-background-warning" />
                    <input type="button" value="alert" class="dv-form-button dv-background-alert" />
            </article>
            
        </section>

        <aside>
            <!-- sub-sub-content goes here -->
        </aside>
        
        <footer>
            <!-- footer goes here -->
        </footer>

    </body>

</html>
