
                <div class="dv-grid-row">
                    <label class="dv-grid-column-8 dv-form-label">Reply content</label>
                    <div class="dv-grid-column-16">
                        
                        <div class="dvbb-container-row dvbb-bbcode-buttons">
                            <a href="#" class="dv-form-button" data-bbcode-tag="b" data-bbcode-target=".dvbb-reply-textarea" title="Bold">
                                <i class="fa fa-fw fa-bold"></i>
                            </a>
                            <a href="#" class="dv-form-button" data-bbcode-tag="i" data-bbcode-target=".dvbb-reply-textarea" title="Italic">
                                <i class="fa fa-fw fa-italic"></i>
                            </a>
                            <a href="#" class="dv-form-button" data-bbcode-tag="u" data-bbcode-target=".dvbb-reply-textarea" title="Underline">
                                <i class="fa fa-fw fa-underline"></i>
                            </a>
                            <a href="#" class="dv-form-button" data-bbcode-tag="s" data-bbcode-target=".dvbb-reply-textarea" title="Strikethrough">
                                <i class="fa fa-fw fa-strikethrough"></i>
                            </a>
                            <a href="#" class="dv-form-button" data-bbcode-tag="color" data-bbcode-target=".dvbb-reply-textarea" title="Color">
                                <i class="fa fa-fw fa-eyedropper"></i>
                            </a>
                            
                            &nbsp; &nbsp; 
                            
                            <a href="#" class="dv-form-button" data-bbcode-tag="left" data-bbcode-target=".dvbb-reply-textarea" title="Align left">
                                <i class="fa fa-fw fa-align-left"></i>
                            </a>
                            <a href="#" class="dv-form-button" data-bbcode-tag="center" data-bbcode-target=".dvbb-reply-textarea" title="Align center">
                                <i class="fa fa-fw fa-align-center"></i>
                            </a>
                            <a href="#" class="dv-form-button" data-bbcode-tag="right" data-bbcode-target=".dvbb-reply-textarea" title="Align right">
                                <i class="fa fa-fw fa-align-right"></i>
                            </a>
                            <a href="#" class="dv-form-button" data-bbcode-tag="justify" data-bbcode-target=".dvbb-reply-textarea" title="Align justify">
                                <i class="fa fa-fw fa-align-justify"></i>
                            </a>
                            
                            &nbsp; &nbsp; 
                            
                            <a href="#" class="dv-form-button" data-bbcode-tag="quote" data-bbcode-target=".dvbb-reply-textarea" title="Quote">
                                <i class="fa fa-fw fa-quote-right"></i>
                            </a>
                            <a href="#" class="dv-form-button" data-bbcode-tag="code" data-bbcode-target=".dvbb-reply-textarea" title="Code">
                                <i class="fa fa-fw fa-code"></i>
                            </a>
                            
                            &nbsp; &nbsp; 
                            
                            <a href="#" class="dv-form-button" data-bbcode-tag="url" data-bbcode-target=".dvbb-reply-textarea" title="Link">
                                <i class="fa fa-fw fa-link"></i>
                            </a>
                            <a href="#" class="dv-form-button" data-bbcode-tag="img" data-bbcode-target=".dvbb-reply-textarea" title="Image">
                                <i class="fa fa-fw fa-image"></i>
                            </a>
                            <a href="#" class="dv-form-button" data-bbcode-tag="video" data-bbcode-target=".dvbb-reply-textarea" title="Video">
                                <i class="fa fa-fw fa-youtube"></i>
                            </a>
                        </div>
                        
                        <?php 
                        // see if we've been given a replyQuote
                        $content = null;
                        if (store::getViewValue('replyQuote')) {
                            $quote = store::getViewValue('replyQuote');
                            $user = (new user())->getById($quote->user_id);
                            $content = '[quote=' . $user->username . ']' . $quote->body . '[/quote]' . PHP_EOL . PHP_EOL;
                        }
                        // see if we've been given content to edit
                        if (store::getViewValue('reply')) {
                            $edit = store::getViewValue('reply');
                            $content = $edit->body;
                        }
                        ?>
                        
                        <textarea name="body" class="dv-form-element dvbb-reply-textarea" style="height: 12rem;"><?=($content ? $content : '');?></textarea>
                        
                        <?php 
                        // if a quote is given, we need to manipulate the textarea to move the caret to the end
                        if ($content) {
                            ?>
                            <script>
                                var target = $('.dvbb-reply-textarea');
                                var content = target.val();
                                target.val('').val(content);
                                target.focus();
                            </script>
                            <?php 
                        }
                        ?>
                    </div>
                </div>
                
                <div class="dv-grid-row">
                    <label class="dv-grid-column-8 dv-form-label"></label>
                    <div class="dv-grid-column-16"><input type="submit" value="post reply" class="dv-form-button" /></div>
                </div>