    <div class="dvbb-container">
        <div class="dvbb-container-header">Registration nearly complete</div>
        <div class="dvbb-container-row">
            <p>
                Congratulations! You should receive a message at the e-mail address you filled in on the previous page,
                which contains a link to validate your e-mail and activate your account.
            </p>
            <p>
                If you still haven't received an e-mail after half an hour or so, make sure to check your e-mail
                provider's spam folder.
            </p>
            <p>
                <a href="<?=store::getRouter()->generate('home')?>">Back to index</a>
            </p>
        </div>
    </div>