<?php
$user = (new user())->getById(store::getViewValue('id'));
?>
<div class="dvbb-container">
    <div class="dvbb-container-header">Profile of <?=$user->username;?></div>
    <div class="dvbb-container-row">
        <?php 
        $topicCount = $user->getTopicCount();
        $replyCount = $user->getReplyCount();
        ?>
        Topics started: <?=$topicCount?><br />
        Replies posted: <?=$replyCount?><br />
    </div>
</div>