<?php
$users = (new user())->getAll();
?>
<div class="dvbb-container">
    <div class="dvbb-container-header">User list</div>
    <div class="dvbb-container-legend dv-grid-row">
        <div class="dv-grid-column-13 dv-text-bold">Username</div>
        <div class="dv-grid-column-2 dv-text-bold">Topics</div>
        <div class="dv-grid-column-2 dv-text-bold">Replies</div>
        <div class="dv-grid-column-7 dv-text-bold">Last Post</div>
    </div>
    <?php 
    foreach ($users as $user) {
        $topics = (new post())->getByFields(array(
            array(
                'key' => 'user_id',
                'match' => '=',
                'value' => $user->id,
            ),
            array(
                'key' => 'forum_id',
                'match' => 'IS NOT',
                'value' => 'NULL',
            ),
        ));
        $topicCount = count($topics);
        $replies = (new post())->getByFields(array(
            array(
                'key' => 'user_id',
                'match' => '=',
                'value' => $user->id,
            ),
            array(
                'key' => 'parent_id',
                'match' => 'IS NOT',
                'value' => 'NULL',
            ),
        ));
        $replyCount = count($replies);
        
        $lastPost = (new post())->getByQuery('SELECT created_at FROM post WHERE user_id = \'' . $user->id . '\' ORDER BY id DESC LIMIT 1');
        ?>
        <div class="dvbb-container-row dv-grid-row">
            <div class="dv-grid-column-13">
                <a href="<?=store::getRouter()->generate('user-profile', array('id' => $user->id));?>"><?=$user->username;?></a>
            </div>
            <div class="dv-grid-column-2"><?=$topicCount?></div>
            <div class="dv-grid-column-2"><?=$replyCount?></div>
            <div class="dv-grid-column-7"><?=(isset($lastPost[0]) ? tool::getDateFormatted($lastPost[0]->created_at) : '--');?></div>
        </div>
        <?php
    }
    ?>
</div>